---
# this play destroys all demo containers
- name: destroy containers on proxmox
  hosts: csgoserver
  gather_facts: no
  # maybe not necessary - sometimes proxmox has locking problems destroying more than one vm at once.
  serial: 1

  vars:
    api_user: root@pam
    api_password: password
    api_host: 172.27.99.100

  tasks:
    - name: stop container
      proxmox:
        hostname: '{{ inventory_hostname }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_password }}'
        api_host: '{{ api_host }}'
        state: stopped
        force: yes
      delegate_to: localhost
      ignore_errors: yes

    - name: destroy container
      proxmox:
        hostname: '{{ inventory_hostname }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_password }}'
        api_host: '{{ api_host }}'
        state: absent
      delegate_to: localhost
      ignore_errors: yes
