---
# tasks file for fctrserver
- name: add apt architecture
  shell: dpkg --add-architecture i386
  register: shell_result
  changed_when: shell_result.rc != 0

- name: install lgsm factorio prerequisites
  apt:
    update_cache: yes
    cache_valid_time: 86400
    name: '{{ item }}'
    state: latest
  with_items:
    - mailutils
    - postfix
    - curl
    - wget
    - file
    - bzip2
    - gzip
    - unzip
    - bsdmainutils
    - python
    - util-linux
    - ca-certificates
    - binutils
    - bc
    - tmux
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - xz-utils

- name: add fctrserver user
  user:
    name: fctrserver
    groups: sudo
    password: '{{ user_password }}'

- name: download lgsm script
  get_url:
    url: https://gameservermanagers.com/dl/linuxgsm.sh
    dest: /home/csgoserver/linuxgsm.sh
    owner: fctrserver
    group: fctrserver
    mode: 0755
    validate_certs: no

- name: check if fctrserver script is installed
  stat:
    path: /home/fctrserver/fctrserver
  register: stat_result

- name: install fctrserver lgsm script
  shell: /bin/bash /home/fctrserver/linuxgsm.sh fctrserver
  become_user: fctrserver
  become: yes
  when: not stat_result.stat.exists

- name: install factorio dedicated server from steam
  block:
    - name: install factorio dedicated server with steamcmd
      shell: /bin/bash /home/fctrserver/fctrserver auto-install
      become_user: fctrserver
      become: yes
      register: shell_result
      failed_when: '"Failure!" in shell_result.stdout'
  rescue:
    - name: check free disk space on fctrserver installation error
      assert:
        that: 
          - "{{ item.mount == '/' and item.size_available >= 17179869184 }}"
        msg: "Disk space is to low. Needs at least 16 GB free disk space for fctrserver."
      with_items: '{{ ansible_mounts }}'
